### ISSUE TITLE
Not a ruby user - how to rectify ?

### ISSUE THREAD

**Issue by bbulkow** [jlund/spotify-export#6]
Is this problem caused by me using ruby2 ?
Ruby2 seems the default on the mac now
# ruby -v
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]

MacBook-Pro:~/dev/spotify-export$ ./bin/spotify-export.rb work-playlist
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./bin/spotify-export.rb:3:in `<main>'

**Comment by axcochrane** [comment]
also having this problem :(

**Comment by jlund** [comment]
You need to install [Bundler](http://bundler.io/). These steps should work:

1. `sudo gem install bundler`
1. `cd spotify-export` (wherever you checked out the repository)
1. `bundle install`
1. `./bin/spotify-export.rb <playlist-file>`

**Comment by celsoandrade** [comment]
After pass this error I'm getting 
`
/home/vagrant/.gem/ruby/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require': Could not load 'active_record/connection_adapters/sqlite3_adapter'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql', 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem to the Gemfile. (LoadError)
`

**Comment by jlund** [comment]
Looks like I forgot to close this. I hope it all worked out! :)
