### ISSUE TITLE
Doesn't appear to be support for web proxies

### ISSUE THREAD

**Issue by DanStevens** [jlund/spotify-export#8]
spotify-export isn't working for me. I believe it is because I am behind a HTTP web proxy. There doesn't appear to be a way to configure spotify-export to use a web proxy.

**Comment by DanStevens** [comment]
I've figured out how to get this working. I have now set the `HTTP_PROXY` environment variable. More information at http://kaamka.blogspot.ro/2009/06/httpproxy-environment-variable.html

**Comment by jlund** [comment]
Thanks for the info!
